# Site settings
title: "HPAA - Hot Pot Astronomical Association"
email: "contact@hpaa.club"
description: "Hot Pot Astronomical Association - Looking up at the universe while enjoying hot pot below"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hpaa.club" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "hpaa_club"
github_username: "robinali34"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  members:
    output: true
    permalink: /members/:name/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "members"
    values:
      layout: "member"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore
  - .github/
  - jekyll-serve.sh
  - preview.sh
  - setup-github.sh
  - DEPLOYMENT.md

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/#about"
  - title: "Members"
    url: "/#members"
  - title: "Gallery"
    url: "/gallery.html"
  - title: "Blog"
    url: "/blog.html"

# Author information
author:
  name: "HPAA Team"
  email: "contact@hpaa.club"
  location: "San Francisco Bay Area, CA"
  bio: "Chinese astronomy enthusiasts organization"

# Formspree ID for contact form
formspree_id: "your-formspree-id-here"

# GitHub Pages settings
github:
  is_project_page: false
  repository_url: "https://github.com/robinali34/hpaa"

# Language and locale settings
lang: "zh-CN"
locale: "zh_CN"

# Jekyll and GitHub Pages versions (compatible with Ruby 2.7)
jekyll: ~> 4.2.0
github-pages: ~> 228

# HTTPS settings
force_ssl: true
secure_headers: true 